/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ZeroMQBackEnd {

using System;
using System.Runtime.InteropServices;

public class A : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal A(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(A obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~A() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ZMQBackEndsPINVOKE.delete_A(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_CoreThreadManagementInterface ThreadingInterface {
    set {
      ZMQBackEndsPINVOKE.A_ThreadingInterface_set(swigCPtr, SWIGTYPE_p_CoreThreadManagementInterface.getCPtr(value));
    } 
    get {
      IntPtr cPtr = ZMQBackEndsPINVOKE.A_ThreadingInterface_get(swigCPtr);
      SWIGTYPE_p_CoreThreadManagementInterface ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_CoreThreadManagementInterface(cPtr, false);
      return ret;
    } 
  }

  public A() : this(ZMQBackEndsPINVOKE.new_A(), true) {
  }

}

}
