/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class A {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected A(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(A obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ZMQBackEndsJNI.delete_A(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setThreadingInterface(SWIGTYPE_p_CoreThreadManagementInterface value) {
    ZMQBackEndsJNI.A_ThreadingInterface_set(swigCPtr, this, SWIGTYPE_p_CoreThreadManagementInterface.getCPtr(value));
  }

  public SWIGTYPE_p_CoreThreadManagementInterface getThreadingInterface() {
    long cPtr = ZMQBackEndsJNI.A_ThreadingInterface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CoreThreadManagementInterface(cPtr, false);
  }

  public A() {
    this(ZMQBackEndsJNI.new_A(), true);
  }

}
