/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ZeroMQBackEnd {

using System;
using System.Runtime.InteropServices;

public class B : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal B(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(B obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~B() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ZMQBackEndsPINVOKE.delete_B(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public A GetA_ptr() {
    IntPtr cPtr = ZMQBackEndsPINVOKE.B_GetA_ptr(swigCPtr);
    A ret = (cPtr == IntPtr.Zero) ? null : new A(cPtr, false);
    return ret;
  }

  public A GetA_copy() {
    A ret = new A(ZMQBackEndsPINVOKE.B_GetA_copy(swigCPtr), true);
    return ret;
  }

  public void DestroyA(A a) {
    ZMQBackEndsPINVOKE.B_DestroyA(swigCPtr, A.getCPtr(a));
  }

  public A a_ptr {
    set {
      ZMQBackEndsPINVOKE.B_a_ptr_set(swigCPtr, A.getCPtr(value));
    } 
    get {
      IntPtr cPtr = ZMQBackEndsPINVOKE.B_a_ptr_get(swigCPtr);
      A ret = (cPtr == IntPtr.Zero) ? null : new A(cPtr, false);
      return ret;
    } 
  }

  public A a_raw {
    set {
      ZMQBackEndsPINVOKE.B_a_raw_set(swigCPtr, A.getCPtr(value));
    } 
    get {
      IntPtr cPtr = ZMQBackEndsPINVOKE.B_a_raw_get(swigCPtr);
      A ret = (cPtr == IntPtr.Zero) ? null : new A(cPtr, false);
      return ret;
    } 
  }

  public B() : this(ZMQBackEndsPINVOKE.new_B(), true) {
  }

}

}
