/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class B {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected B(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(B obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ZMQBackEndsJNI.delete_B(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public A GetA_ptr() {
    long cPtr = ZMQBackEndsJNI.B_GetA_ptr(swigCPtr, this);
    return (cPtr == 0) ? null : new A(cPtr, false);
  }

  public A GetA_copy() {
    return new A(ZMQBackEndsJNI.B_GetA_copy(swigCPtr, this), true);
  }

  public void DestroyA(A a) {
    ZMQBackEndsJNI.B_DestroyA(swigCPtr, this, A.getCPtr(a), a);
  }

  public void setAaa_ptr(A value) {
    ZMQBackEndsJNI.B_aaa_ptr_set(swigCPtr, this, A.getCPtr(value), value);
  }

  public A getAaa_ptr() {
    long cPtr = ZMQBackEndsJNI.B_aaa_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new A(cPtr, false);
  }

  public void setAaa_raw(A value) {
    ZMQBackEndsJNI.B_aaa_raw_set(swigCPtr, this, A.getCPtr(value), value);
  }

  public A getAaa_raw() {
    long cPtr = ZMQBackEndsJNI.B_aaa_raw_get(swigCPtr, this);
    return (cPtr == 0) ? null : new A(cPtr, false);
  }

  public B() {
    this(ZMQBackEndsJNI.new_B(), true);
  }

}
