/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ZMQBackEndsJNI {
  public final static native long ZMQBackEnd_get();
  public final static native void A_ThreadingInterface_set(long jarg1, A jarg1_, long jarg2);
  public final static native long A_ThreadingInterface_get(long jarg1, A jarg1_);
  public final static native long new_A();
  public final static native void delete_A(long jarg1);
  public final static native long B_GetA_ptr(long jarg1, B jarg1_);
  public final static native long B_GetA_copy(long jarg1, B jarg1_);
  public final static native void B_DestroyA(long jarg1, B jarg1_, long jarg2, A jarg2_);
  public final static native void B_aaa_ptr_set(long jarg1, B jarg1_, long jarg2, A jarg2_);
  public final static native long B_aaa_ptr_get(long jarg1, B jarg1_);
  public final static native void B_aaa_raw_set(long jarg1, B jarg1_, long jarg2, A jarg2_);
  public final static native long B_aaa_raw_get(long jarg1, B jarg1_);
  public final static native long new_B();
  public final static native void delete_B(long jarg1);
}
