/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ZMQBackEnds {
  public static SWIGTYPE_p_BackEnd getZMQBackEnd() {
    return new SWIGTYPE_p_BackEnd(ZMQBackEndsJNI.ZMQBackEnd_get(), true);
  }

}
