/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ZeroMQBackEnd {

using System;
using System.Runtime.InteropServices;

public class ZMQBackEnds {
  public static SWIGTYPE_p_BackEnd ZMQBackEnd {
    get {
      SWIGTYPE_p_BackEnd ret = new SWIGTYPE_p_BackEnd(ZMQBackEndsPINVOKE.ZMQBackEnd_get(), true);
      return ret;
    } 
  }

}

}
