/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MQCloud {

using System;
using System.Runtime.InteropServices;

public class CorePublishingSocketInterface : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CorePublishingSocketInterface(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CorePublishingSocketInterface obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CorePublishingSocketInterface() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MQCloudPINVOKE.delete_CorePublishingSocketInterface(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f___p_void CoreCreatePublishingSocket {
    set {
      MQCloudPINVOKE.CorePublishingSocketInterface_CoreCreatePublishingSocket_set(swigCPtr, SWIGTYPE_p_f___p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CorePublishingSocketInterface_CoreCreatePublishingSocket_get(swigCPtr);
      SWIGTYPE_p_f___p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f___p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_int_p_q_const__CString__void CoreBindPublishingSocket {
    set {
      MQCloudPINVOKE.CorePublishingSocketInterface_CoreBindPublishingSocket_set(swigCPtr, SWIGTYPE_p_f_int_p_q_const__CString__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CorePublishingSocketInterface_CoreBindPublishingSocket_get(swigCPtr);
      SWIGTYPE_p_f_int_p_q_const__CString__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int_p_q_const__CString__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_int_p_q_const__CoreMessage__void CorePublishMessage {
    set {
      MQCloudPINVOKE.CorePublishingSocketInterface_CorePublishMessage_set(swigCPtr, SWIGTYPE_p_f_int_p_q_const__CoreMessage__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CorePublishingSocketInterface_CorePublishMessage_get(swigCPtr);
      SWIGTYPE_p_f_int_p_q_const__CoreMessage__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int_p_q_const__CoreMessage__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_void__void CoreDeletePublishingSocket {
    set {
      MQCloudPINVOKE.CorePublishingSocketInterface_CoreDeletePublishingSocket_set(swigCPtr, SWIGTYPE_p_f_p_void__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CorePublishingSocketInterface_CoreDeletePublishingSocket_get(swigCPtr);
      SWIGTYPE_p_f_p_void__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
      return ret;
    } 
  }

  public CorePublishingSocketInterface() : this(MQCloudPINVOKE.new_CorePublishingSocketInterface(), true) {
  }

}

}
