/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MQCloud {

using System;
using System.Runtime.InteropServices;

public class CoreSubscriberSocketInterface : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CoreSubscriberSocketInterface(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CoreSubscriberSocketInterface obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CoreSubscriberSocketInterface() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MQCloudPINVOKE.delete_CoreSubscriberSocketInterface(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_f_p_q_const__CoreMessage__void__int CoreCreateSubscribingSocket {
    set {
      MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreCreateSubscribingSocket_set(swigCPtr, SWIGTYPE_p_f_p_f_p_q_const__CoreMessage__void__int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreCreateSubscribingSocket_get(swigCPtr);
      SWIGTYPE_p_f_p_f_p_q_const__CoreMessage__void__int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_f_p_q_const__CoreMessage__void__int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_int_p_q_const__CString__void CoreConnectSubscribingSocket {
    set {
      MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreConnectSubscribingSocket_set(swigCPtr, SWIGTYPE_p_f_int_p_q_const__CString__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreConnectSubscribingSocket_get(swigCPtr);
      SWIGTYPE_p_f_int_p_q_const__CString__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int_p_q_const__CString__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_int__void CoreDeleteSubscribingSocket {
    set {
      MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreDeleteSubscribingSocket_set(swigCPtr, SWIGTYPE_p_f_int__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.CoreSubscriberSocketInterface_CoreDeleteSubscribingSocket_get(swigCPtr);
      SWIGTYPE_p_f_int__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_int__void(cPtr, false);
      return ret;
    } 
  }

  public CoreSubscriberSocketInterface() : this(MQCloudPINVOKE.new_CoreSubscriberSocketInterface(), true) {
  }

}

}
