/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MQCloud {

using System;
using System.Runtime.InteropServices;

public class ExtensiabiletyEventsHandler : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ExtensiabiletyEventsHandler(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ExtensiabiletyEventsHandler obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ExtensiabiletyEventsHandler() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MQCloudPINVOKE.delete_ExtensiabiletyEventsHandler(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_f_p_q_const__ServiceId__void OnNodeConnectedToOther {
    set {
      MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnNodeConnectedToOther_set(swigCPtr, SWIGTYPE_p_f_p_q_const__ServiceId__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnNodeConnectedToOther_get(swigCPtr);
      SWIGTYPE_p_f_p_q_const__ServiceId__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_q_const__ServiceId__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_q_const__ServiceId__void OnNodeConnectedToThis {
    set {
      MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnNodeConnectedToThis_set(swigCPtr, SWIGTYPE_p_f_p_q_const__ServiceId__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnNodeConnectedToThis_get(swigCPtr);
      SWIGTYPE_p_f_p_q_const__ServiceId__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_q_const__ServiceId__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_q_const__CoreMessage__void OnMessage {
    set {
      MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnMessage_set(swigCPtr, SWIGTYPE_p_f_p_q_const__CoreMessage__void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = MQCloudPINVOKE.ExtensiabiletyEventsHandler_OnMessage_get(swigCPtr);
      SWIGTYPE_p_f_p_q_const__CoreMessage__void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_q_const__CoreMessage__void(cPtr, false);
      return ret;
    } 
  }

  public ExtensiabiletyEventsHandler() : this(MQCloudPINVOKE.new_ExtensiabiletyEventsHandler(), true) {
  }

}

}
